### ISSUE TITLE
Strange behaviour - slow to open on click

### ISSUE THREAD

**Issue by JTD420** [wire-elements/spotlight#106]
Seems to work fine when using the commands `CTRL/CMD` + `K` or `CTRL/CMD` + `/` but if I try to open the spotlight when a user presses on a search button in my navigation it can take 2-3+ seconds before it actually appears making it seem like it's completely unresponsive at first.

Any reason why this could be happening?

**Comment by PhiloNL** [comment]
I would recommend investigating using your dev tools to get some more insights into what is happening. Is it making an XHR request that takes long to load for example?

**Comment by JTD420** [comment]
> I would recommend investigating using your dev tools to get some more insights into what is happening. Is it making an XHR request that takes long to load for example?

Yes that's correct, it was making an XHR request that was taking a very long time to load. I wasn't able to resolve the problem in the end so I ended up removing the package from my project h owever I may try to reintegrate it at a later stage. For now I'll close this issue.
