### ISSUE TITLE
Search multiple models

### ISSUE THREAD

**Issue by sebreunion** [wire-elements/spotlight#110]
Hi,

Thanks for your great work.

I'd like to be able to search multiple models within one command. Like offer the ability to search Product & Category.

Is there a way to somehow add something to identify the model for each result entry and be able to manage each case differently ? As simple as forwarding to different route based on the result selected by the user.

I guess i could create multiple command, one per model to search but i'd like a global search.

Thx for your help

**Comment by PhiloNL** [comment]
Hi @sebreunion,

This is not possible with the free version, however, you might want to look at the pro version.
If you hit cmd+k on the [following page](https://wire-elements.dev/pro) you can see the pro version in action.
