### ISSUE TITLE
Focus when using token scope and deleting the scope in the UI

### ISSUE THREAD

**Issue by nick-wilkins** [wire-elements/spotlight#117]
When I'm using the token / scope ability, and am on a particular page that uses that scope, when I hit the backspace key / delete the scope in the UI, the input loses focus and the user can't start typing without using the mouse to re-focus the search box (or close and open it again)

**Comment by PhiloNL** [comment]
Hey @nick-wilkins,
Could you share some more details, like which browser you are using, and maybe record a screencast?

For example, when I visit the following page https://wire-elements.dev/docs/getting-started/spotlight-component and hit CMD+K, and use backspace to remove the active scope, the focus remains—tested on Chrome and Safari.

Thanks!

**Comment by nick-wilkins** [comment]
Hi @PhiloNL - ahh yes I see. This must be an implementation bug somewhere along the line with what I'm doing (the link you provided works fine, same browser etc), or from a certain setup of token / scope combinations. I'll investigate and let you know if I get more info on this. Thanks
