### ISSUE TITLE
Livewire v3 support

### ISSUE THREAD

**Issue by PhiloNL** [wire-elements/spotlight#120]
[It's work in progress, please read the following announcement](https://github.com/wire-elements/modal/discussions/329)

**Comment by pxlrbt** [comment]
@PhiloNL In the announcement you mention `wire-elements/modal`. Any feedback on your plans with Spotlight?

**Comment by PhiloNL** [comment]
@pxlrbt just tagged v2 to support Livewire v3 😄 
https://github.com/wire-elements/spotlight/releases

**Comment by pxlrbt** [comment]
Damn, means I need to put in work now 😅
Thanks for upgrading this to LW3. 👍🏼

**Comment by mbardelmeijer** [comment]
@PhiloNL is there an upgrade guide available for going from 1.0 to 2.0? :)

**Comment by PhiloNL** [comment]
> @PhiloNL is there an upgrade guide available for going from 1.0 to 2.0? :)

composer update should be all there is :)

**Comment by mbardelmeijer** [comment]
@PhiloNL check! Asked as I ran into the following issue after upgrading: `Property [$id] not found on component: [livewire-ui-spotlight]`. Found it was due to the view file being overruled and was changed in the default view from `$this->id` to `$this->id()`. Just for other people finding this!

**Comment by developerinvnr** [comment]
@mbardelmeijer same issue arrive in my application. how to resolved it ?
thanks in advance

**Comment by PhiloNL** [comment]
> @mbardelmeijer same issue arrive in my application. how to resolved it ? thanks in advance

Make sure you republish your views and clear your view caches. That should solve the issue.
