### ISSUE TITLE
Dynamic creation of spotlight commands.

### ISSUE THREAD

**Issue by kirgus** [wire-elements/spotlight#127]
Good afternoon.

Is it possible to dynamically create spotlight commands?

For example, to solve such a problem, there is a table in the database with projects.
And it would be great to jump right into a certain project.

CMD + / → "Project name 1" → route("project_name_1")

**Comment by PhiloNL** [comment]
Hi @kirgus,
I think the Pro version would meet your needs:
https://wire-elements.dev/docs/getting-started/spotlight-component

This supports scopes, if you click the link above and hit CMD + / you will see you are already scoped in the documentation and can use backspace to go one level up. You can implement your own commands and actions to do almost anything.
