### ISSUE TITLE
Feature Request: Add bootstrap styling

### ISSUE THREAD

**Issue by Restingo** [wire-elements/spotlight#32]
Add bootstrap theme for styling.

**Comment by PhiloNL** [comment]
Hi @Restingo,
Have you tried setting `include_css` to `true`? This will include the required CSS for Spotlight and should work with other CSS frameworks like Bootstrap.

**Comment by Restingo** [comment]
Hi @PhiloNL, thanks for your fast reply! I've tried it but it destroys my template (I'm using AdminLTE from https://github.com/jeroennoten/Laravel-AdminLTE) because it includes Normalize.css I think?

**Comment by Restingo** [comment]
![image](https://user-images.githubusercontent.com/84022569/124028902-d1cc3200-d9f4-11eb-9845-180e7dd165a9.png)

Left side is without css, right side is with css.

**Comment by Restingo** [comment]
@PhiloNL any idea?

**Comment by TechTailor** [comment]
Would also appreciate a way to enable/add custom css styling.
