### ISSUE TITLE
Close already open modals when a new modal opens with Spotlight?

### ISSUE THREAD

**Issue by seabasss** [wire-elements/spotlight#44]
This is really cool!

I'm trying it out with modals and it works pretty well, but is there any way to close all other modals if I open a new one with Spotlight? This didn't work:

```
public function execute(Spotlight $spotlight)
{
    $spotlight->emit('closeModal'); // forceful too if possible
    $spotlight->emit('openModal', 'create-user');
}
```

Also, is there any way to change the standard `Logout out of your account` to `Log out of your account`.

Edit // I guess I can just re-create that class in my Spotlight folder.

Thanks again, love it!

**Comment by PhiloNL** [comment]
I don't have a solution for this at this time but if you have an idea on how to tackle this feel free to create a PR :)
