### ISSUE TITLE
Results not shown, but indigo border appears

### ISSUE THREAD

**Issue by thomasjohnkane** [wire-elements/spotlight#49]
When search results are found, the indigo bottom border is shown, but no results are displayed. Pressing enter will trigger the first matching command.

<img width="619" alt="Screen Shot 2021-10-30 at 4 24 19 PM" src="https://user-images.githubusercontent.com/8945177/139561889-7fd094ff-0c04-437d-8279-eba7e5d2a4ce.png">

In the particular example, the registered commands are EditPolicy and ViewPolicy, both of which should be shown as options in the dropdown menu.

**Comment by thomasjohnkane** [comment]
Works on a fresh install, must just be an issue with my Tailwind or Livewire version. Closing.

**Comment by liamseys** [comment]
I have this issue too, why is this happening?
