### ISSUE TITLE
Commands work but search gives console errors

### ISSUE THREAD

**Issue by marchampson** [wire-elements/spotlight#74]
Love the package and sure this is something with my setup but I've tried a number of things and hit the same wall. When you search an indigo bar appears but it doesn't activate and the console fills with errors:
![image](https://user-images.githubusercontent.com/988694/157411812-896d8e97-01c9-45df-a28c-649cbe14de35.png)
I have alpine installed as a module, it was 3.2 and now 3.9.1 - alpine components work.
Any thoughts? 
Thanks.

**Comment by kerynegan** [comment]
Hi @PhiloNL  - I'm having the same problem, though I'm using Alpine CDN. 

My command (open a modal) does execute when I finish typing and hit enter, but it seems to be trying to execute every letter of the query as I type and throwing Console errors all the while.

Here's (an attempt at uploading) a gif screenshot in action.
![spotlight2](https://user-images.githubusercontent.com/35839424/163292326-66962885-bf7f-4f65-aacd-efb321497080.gif)

Any idea as to where to start to fix this? Happy to provide more information if that would be helpful. Thanks!

**Comment by PhiloNL** [comment]
I've tested this with 3.9.1 and it works. It might be related to the order, the following works for me:

```
// blade
@livewireStyles

@livewire('livewire-ui-spotlight')
@livewireScripts

<script src="/app.js"></script>
```

```
// app.js
require('../../vendor/wire-elements/modal/resources/js/modal')
import Alpine from 'alpinejs'

window.Alpine = Alpine
Alpine.start()
```
