### ISSUE TITLE
Spotlight doesn't react on click event dispatch 

### ISSUE THREAD

**Issue by syntafin** [wire-elements/spotlight#98]
Good day,

months ago the dispatch event on a button to open spotlight on mobile stopped working, as we are still in early development, it wasn't necessary to fix it. But soon we will go to launch phase.

At the moment the button has a dispatcher in a alpine.js Click event that look like this:

``@click="$dispatch('toggle-spotlight')"``

This way it is described in the docs.
I can't see any log message in the console.
Someone an idea?

Live Preview of the problem:
https://dev.xivdata.com

The toggle button (search symbol) only appears below MD Viewport

**Comment by PhiloNL** [comment]
Hi there,
`@click` only works on a Alpine scoped element, so you will need to add `x-data` to the button or a parent element.
